version: "3.8"

services:

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  user:
    build: ./user-service
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/microdb
    ports:
      - "5001:5000"
    depends_on:
      - mongo

  order:
    build: ./order-service
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/microdb
    ports:
      - "5002:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_USER_URL=http://user:5000
      - REACT_APP_ORDER_URL=http://order:5000
    ports:
      - "3000:3000"
    depends_on:
      - user
      - order
